# -*- coding: utf-8 -*-
"""mathops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uQC33rCC2TtKC-5C5MXidbrK5WouovaV
"""

import numpy

dir(numpy)

import numpy as np

a=np.array([2,8,4,9,55]) #creating 1D array

type(a)  #checking type of a

b=np.array([7,8,6,55,4])

a

b

a[0]   #0th element

a[0+2]

a+b  #simple type addition of same dimensions ARRAY

a*b   #multiply same d array

a+2   #adding 2 to each elemnt of array A

a+b+2   #simple operation bw 2 arrays

a*2  #multiply by 2 each elemnets of array A

a**3  #finding cube of each elemnt of array A