# -*- coding: utf-8 -*-
"""mathops2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JlODjJaPNvm1KZ7OMOx6kuL1h2EBYSac
"""

import numpy as np

x=np.array([[2,3,4],[4,5,6]])  #2D array of 2x3 ==> x[2][3]

np

x

x[0][0]  #first element

x[1][2] #last elemnt

x+7

x*7

x**2

x[0]

x[1]

z=np.array([1,7],[2,8],[3,9],[4,6])

z=np.array([[1,7],[2,8],[3,9],[4,6]])

z.shape  #order of matrix

#z[0:2]

z[0:]

z[0:,0]

z[0:,0:]

z[0:2,0:]

z[0:2,0:2]

z[0:2,1]

z[0:2,0]

z[0:,[0,2]]

z[0:,[0,1]]   #

z[0:2,[1]]  #scnd column among frst 2 rows

z[:,[0,3]]

z[[0,3],[0,3]]

z[[0,2],1]

b=np.array([[1,9,7],[3,2,8],[4,5,6],[2,9,0]])

b

b.shape

b[0:,1]

b[1:3,[1,2]]

b[1:,1]

z.reshape(2,4)

b1=b.reshape(4,3)

b1=b.reshape(3,4)   #

b1

np.zeros((3,6))       #assign ZEROS to all values in 2D array

np.zeros((3,6),dtype=int)    #assign ZEROS to all postion in 2D array but in INTEGER

np.full((4,5),4)   #fill with particular number that is 4

